# Generated by Django 6.1 on 2026-08-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content_viwe_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date']},
        ),
    ]
